### ISSUE TITLE
Starter kit 1.1.0 is missing?

### ISSUE THREAD

**Issue by rpardini** [googlecodelabs/psk-es2015#1]
The link to https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.1.0/polymer-starter-kit-1.1.0.zip (green button in the codelab) is 404'ing. I can only find links to 1.0.3, which I don't think is the right thing, or is it?

**Comment by nicolasgarnier** [comment]
Yes :/ Polymer Starter Kit 1.1.0 was supposed to release before the Polymer summit but unfortunately it got delayed. 1.0.3 can do but the best is to get Polymer starter kit from master which is almost equivalent to what 1.1.0 will be: https://github.com/PolymerElements/polymer-starter-kit/archive/master.zip

Sorry about that. I'll try to update the codelab asap.

**Comment by rpardini** [comment]
Thanks Nicolas. What I used for the code lab was actually yeoman + generator-polymer, which I think embeds 1.0.3 and works beautifully for the ES6 codelab. 

``` Shell
npm install -g yo generator-polymer grunt grunt-cli
mkdir -p es2015polymer && cd es2015polymer
yo polymer
npm install && bower install
grunt serve
```

**Comment by nicolasgarnier** [comment]
I'm glad it worked for you! FYI Polymer Starter Kit 1.1.0 has been released now :) (I'll need to revert the codelab which now points to master/

Cheers!
