### ISSUE TITLE
Need to run manual bower install 

### ISSUE THREAD

**Issue by philsurette** [googlecodelabs/psk-es2015#3]
I got this error running under windows (7):
[20:20:23] Error in plugin 'gulp-vulcanize'
Message:
    ENOENT, open 'C:\dev\polymer\polymer-starter-kit-1.1.1\dist\bower_components\webcomponentsjs\webcomponents-lite.min.js'

solution was to run 'bower install '

**Comment by nicolasgarnier** [comment]
Hey @philsurette: Running `bower install` is listed in the **Getting set up** section (Step 2). Perhaps you missed it?

Cheers!
