### ISSUE TITLE
modified files not being watched

### ISSUE THREAD

**Issue by philsurette** [googlecodelabs/psk-es2015#5]
In order for the browserSync for this project to be of any use, I found that I had to add a new task to copy .js and .html changes to the .tmp folder which is what the server is watching first.

I added this task:

``` javascript
// Scan your HTML for assets & optimize them
gulp.task('copy:tmp', function () {
 return gulp.src(['app/**/*.{js,html}'])
   .pipe($.sourcemaps.init())
   .pipe($.if('*.html', $.crisper())) // Extract JS from .html files
   .pipe($.if('*.js', $.babel()))
   .pipe($.sourcemaps.write('.'))
   .pipe(gulp.dest('.tmp/'))
});
```

and added it to `gulp.watch`

``` javascript
  gulp.watch(['app/**/*.{js,html}'], ['copy:tmp', reload]);
```

**Comment by nicolasgarnier** [comment]
Hey @philsurette In theory this is what adding the following lines should do:

``` js
gulp.watch(['app/**/*.html'], ['js', reload]); // Added 'js' and the array here!
...
gulp.watch(['app/{scripts,elements}/**/{*.js,*.html}'], ['jshint', 'js']); // Added 'js' and the array here!
```

The `js` task is equivalent to your `copy:tmp` task above and the 2 `gulp.watch` above should effectively be watching all js and html files changes...
