### ISSUE TITLE
Polymer is not a function when using gulp serve (but work using gulp serve:dist)

### ISSUE THREAD

**Issue by jlambe** [googlecodelabs/psk-es2015#9]
Hi,
I followed the tutorial but since the rewrite of the script for the "awesome-meme" custom element to ES6 - ES2015 class, it doesn't work and keeps telling that Polymer is not a function when using the command `gulp serve`. The tutorial also advice to rewrite the `my-list.html` and `my-greeting.html` elements which trigger the same error.

I tried to change the paths to the `polymer.html` component, but without any luck. I found there was an issue from [vulcanize](https://github.com/Polymer/vulcanize/issues/160) but nobody found a solution.

Anyway, the `gulp serve:dist` command works perfectly. I haven't check the tasks for `gulp serve:dist` but the console tells this right after `Starting vulcanize`:
- Ignoring duplicate element definition: undefined
- Ignoring duplicate element definition: undefined
  `Finished vulcanize`

Hope this might help others having the same issue.

**Comment by robdodson** [comment]
It's possibly related to us changing the location of the bower_components directory in PSK. Taking a look at tuning up this example today

**Comment by robdodson** [comment]
I noticed that if there are any JS errors anywhere in the page, you'll see this message. In my case I messed something up in routing.html and it started saying this. Fixing the error in routing.html resolved things. So I guess this is something to keep an eye out for.
